title: Plaba's blog (unique title here)
description: >- 
  This is my blog. I write about stuff.
baseurl: ""
url: "https://plaba.github.io" 
github_username: plaba

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed